apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  labels:
    app: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: nginx
        image: 51778792314.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PGHOST
          valueFrom:
           secretKeyRef:
             name: secret-db
             key: PGHOST
        - name: PGUSER
          valueFrom:
           secretKeyRef:
             name: secret-db
             key: PGUSER
        - name: PGDATABASE
          valueFrom:
           secretKeyRef:
             name: secret-db
             key: PGDATABASE
        - name: PGPASSWORD
          valueFrom:
           secretKeyRef:
             name: secret-db
             key: PGPASSWORD
